### ISSUE TITLE
What would be the equivalent pinout if this software is used on a regular Pi Pico?

### ISSUE THREAD

**Issue by hachirokumiku** [wickerwaka/PicoROM#7]
What is the Pinout for ADDRESS and DATA as laid out on a standard Pi Pico? I.e Does DATA 0-7 correspond to GPIO0,1,2,3,4,5,6,7 etc?

**Comment by wickerwaka** [comment]
Happy to answer, but I don't understand the question.

**Comment by hachirokumiku** [comment]
Ah, I see it uses an I/O Expander, thanks anyway.

**Comment by hachirokumiku** [comment]
> Happy to answer, but I don't understand the question.

I expanded and rephrased my question, in short, i see you built a custom board, but could this be used with a regular pi pico?

**Comment by wickerwaka** [comment]
The address pins are GPIO 0-17 and the data pins are GPIO are 22-29. The Pico Pi is 40 pins while this is intended to be used in place of 32-pin ROMS and the layout of the pins with the pico pi would not be compatible with any standard ROM pin layouts because of how the GND and power pins are placed.

**Comment by dshadoff** [comment]
...Not to mention that there are several GPIOs which aren't exposed on the Pico board (GPIO 23, 24, 25, 29), so even if one created a "converter" board, and even if that converter board didn't have problems with physical dimensions, it still wouldn't be sufficient electrically.
